### ISSUE TITLE
Latest Update Breaks Assemble v0.6.0

### ISSUE THREAD

**Issue by avr** [jonschlinkert/parser-front-matter#3]
I have some page templates in an Assemble project that suddenly aren't reading YAML options (specifically a "layout" setting).

If I change Assemble's package.json to:

```
"parser-front-matter": "jonschlinkert/parser-front-matter#e34a50248e3b43a7e8afcd2bf2486344ad3781e6",
```

My Assemble projects builds as expected.  Not sure if this is helpful here or in the Assemble project.

**Comment by jonschlinkert** [comment]
thanks for reporting! I'll get this fixed asap

**Comment by jonschlinkert** [comment]
sorry about the issue. I believe the problem was caused by using `extend` instead of `merge`.   published as v1.2.4.

**Comment by jonschlinkert** [comment]
please reopen this if it isn't fixed for you.

**Comment by avr** [comment]
Thanks Jon - works great!

**Comment by jonschlinkert** [comment]
:+1:
