### ISSUE TITLE
Trigger new Travis build to update badge

### ISSUE THREAD

**Issue by mootari** [jonschlinkert/parser-front-matter#5]
Just a minor nitpick: The latest Travis build (5 months ago) failed for Node 0.10 and 0.12 due to gray-matter using `const` in its code. This was fixed in gray-matter 3.0.6. The current Travis badge implies problems that no longer exist.

**Comment by jonschlinkert** [comment]
good catch, thanks for the heads up! Build has been restarted, I'll close when it's confirmed. thanks!
